### ISSUE TITLE
Attempt to invoke virtual method 'void com.facebook.marketing.ViewIndexer.unschedule()' on a null object reference

### ISSUE THREAD

**Issue by thangvo406** [underscopeio/react-native-facebook-account-kit#181]
I use react-native-facebook-account-kit library. The build is uploaded production. I get this error. But I don't know where the error

Error detail blow

`Fatal Exception: java.lang.RuntimeException: Unable to pause activity {com.abc.xyz/com.facebook.accountkit.ui.AccountKitActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.marketing.ViewIndexer.unschedule()' on a null object reference
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3914)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3880)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3854)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3828)
       at android.app.ActivityThread.-wrap15(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1611)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6530)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

* React Native Account Kit version: 0.10.1
* React Native version: 0.55.0
* Platform: Android

**Comment by Donhv** [comment]
same ....

**Comment by thangvo406** [comment]
@Donhv Are your issue resolved?

**Comment by Donhv** [comment]
no solution.

**Comment by Donhv** [comment]
i fix it by upgradge fbsdk

**Comment by jpgarcia** [comment]
Guys, we just published a new **1.2.0** version of the library which upgrades the SDK to the latest **5.+** version.

This version also allow users to verify their phone using **Whatsapp**!

I'm closing this for now. Please feel free to reopen it if the issue persists

**Comment by vishaldhanotiya** [comment]
Change this one

> implementation 'com.facebook.android:facebook-android-sdk:4.34.0'

 to this

> implementation 'com.facebook.android:facebook-login:[4,5)'
