### ISSUE TITLE
Release build is crashing

### ISSUE THREAD

**Issue by zsajjad** [underscopeio/react-native-facebook-account-kit#52]
### Issue Description

App is crashing after certain time in production! Google Pre-Launch report also showing crash.

### Steps to Reproduce / Code Snippets

Cannot reproduce it everytime

#### Expected Results

Crash

### Additional Information

* React Native Account Kit version: 0.5.2
* React Native version: 0.36.0
* Platform(s) (iOS, Android, or both?): Android

### Error Reports:
```
FATAL EXCEPTION: main
 Process: com.fetchsky.peekaboo, PID: 9569
 java.lang.NullPointerException
 	at com.facebook.accountkit.internal.AppEventsLogger.handleResponse(AppEventsLogger.java:526)
 	at com.facebook.accountkit.internal.AppEventsLogger.access$600(AppEventsLogger.java:57)
 	at com.facebook.accountkit.internal.AppEventsLogger$4.onCompleted(AppEventsLogger.java:510)
 	at com.facebook.accountkit.internal.AccountKitGraphRequestAsyncTask.onPostExecute(AccountKitGraphRequestAsyncTask.java:188)
 	at com.facebook.accountkit.internal.AccountKitGraphRequestAsyncTask.onPostExecute(AccountKitGraphRequestAsyncTask.java:42)
 	at android.os.AsyncTask.finish(AsyncTask.java:632)
 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:136)
 	at android.app.ActivityThread.main(ActivityThread.java:5001)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:515)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
 	at dalvik.system.NativeStart.main(Native Method)
```

```
FATAL EXCEPTION: main
 Process: com.fetchsky.peekaboo, PID: 25137
 java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.accountkit.internal.AccountKitRequestError com.facebook.accountkit.internal.AccountKitGraphResponse.getError()' on a null object reference
 	at com.facebook.accountkit.internal.AppEventsLogger.handleResponse(AppEventsLogger.java:526)
 	at com.facebook.accountkit.internal.AppEventsLogger.access$600(AppEventsLogger.java:57)
 	at com.facebook.accountkit.internal.AppEventsLogger$4.onCompleted(AppEventsLogger.java:510)
 	at com.facebook.accountkit.internal.AccountKitGraphRequestAsyncTask.onPostExecute(AccountKitGraphRequestAsyncTask.java:188)
 	at com.facebook.accountkit.internal.AccountKitGraphRequestAsyncTask.onPostExecute(AccountKitGraphRequestAsyncTask.java:42)
 	at android.os.AsyncTask.finish(AsyncTask.java:636)
 	at android.os.AsyncTask.access$500(AsyncTask.java:177)
 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:145)
 	at android.app.ActivityThread.main(ActivityThread.java:6837)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:372)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

Need early response as my app is production!

**Comment by gaguirre** [comment]
It seems to be related to [this issue](https://developers.facebook.com/bugs/323721821335576/)
Apparently it's a Facebook SDK's bug on 'no internet connection' scenario.

**Comment by duongnv1996** [comment]
Anyone fixed this issues?

**Comment by IanWambai** [comment]
Nope, our production app is crashing like hell at the moment. Might have to shelve that AccountKit feature until they fix the issue.

**Comment by gaguirre** [comment]
Hi to everyone @IanWambai @duongnv1996 @zsajjad 
Look at the FB issue posted above, it's fixed but not released yet.
Once released, building a new `.apk` should be enough to solve the problem (because the SDK version is not fixed in our `build.gradle`)

**Comment by gaguirre** [comment]
@zsajjad @duongnv1996 @IanWambai the issue should be fixed in the latest Facebook SDK release (4.18.0) according to [this](https://developers.facebook.com/docs/android/change-log-4x).

Could you check it's working? You just need to re-build your app and gradle should get the latest version.
Thanks!

**Comment by zsajjad** [comment]
Its fixed! Thanks :+1:

**Comment by gaguirre** [comment]
Great! 😃
